version: "3"
services:
  pg-tasks:
    container_name: pg-tasks
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_PASSWORD=postgres
  sonarqube:
    container_name: sonar
    image: sonarqube:7.9.2-community
    networks:
      - sonarnet
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
      - "9000:9000"
  db:
    container_name: pg-sonar
    image: postgres:latest
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks: 
  sonarnet:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
  sonarqube_bundled-plugins: